const EXPO_PUBLIC_API_BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL || 'http://localhost:8080';
const EXPO_PUBLIC_MODEL_BASE_URL = process.env.EXPO_PUBLIC_MODEL_BASE_URL || 'http://localhost:8083';

export { EXPO_PUBLIC_API_BASE_URL, EXPO_PUBLIC_MODEL_BASE_URL};